services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_HOST}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 40
      start_period: 1s
      timeout: 10s
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --skip-character-set-client-handshake
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - king

  redis:
    image: redis:alpine
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      retries: 5
      start_period: 1s
      timeout: 10s
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    networks:
      - king

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 5s
      retries: 60
      start_period: 5s
      timeout: 10s
    restart: always
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    networks:
      - king

  springboot:
    build:
      context: ./king-backend
      dockerfile: ./Dockerfile
    container_name: springboot
    restart: always
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      elastic:
        condition: service_healthy
    expose:
      - "8080"
    networks:
      - king

  nginx:
    image: nginx:1.27.3-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./king/dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - springboot
    networks:
      - king

volumes:
  mysql-data:
  redis-data:
  elastic-data:

networks:
  king:
    driver: bridge
